//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfaAPJobs.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wfaAPJobs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J {
            get {
                object obj = ResourceManager.GetObject("J", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server=localhost;Port=3306;User Id=admin_jobs;Password=mh-PoADIgtd5dPd_;DataBase=bddjobs.
        /// </summary>
        internal static string MARIADB_SERVER_PATH {
            get {
                return ResourceManager.GetString("MARIADB_SERVER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UPDATE utilisateur SET isBan = @isBan WHERE idUser = @idUser;.
        /// </summary>
        internal static string REQ_BAN_OR_UNBAN_ACCOUNT {
            get {
                return ResourceManager.GetString("REQ_BAN_OR_UNBAN_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DELETE FROm activite WHERE idAct = @idAct;.
        /// </summary>
        internal static string REQ_DELETE_ACTIVITY {
            get {
                return ResourceManager.GetString("REQ_DELETE_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT U.*, S.intitStatut FROM utilisateur U INNER JOIN statut S ON S.idStatut = U.idStatut WHERE isAdmin = 0;.
        /// </summary>
        internal static string REQ_GET_ACCOUNTS {
            get {
                return ResourceManager.GetString("REQ_GET_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT O.*,U.*,E.nom nomEmployeur,E.prenom prenomEmployeur,E.civilite civEmployeur, C.idStatut statutCandid FROM candidature C INNER JOIN offre O ON O.idOffre = C.idOffre INNER JOIN utilisateur U ON U.idUser = C.idEtudiant INNER JOIN utilisateur E ON E.idUser = O.idEmployeur;.
        /// </summary>
        internal static string REQ_GET_CANDIDATURES {
            get {
                return ResourceManager.GetString("REQ_GET_CANDIDATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT * FROM evenement;.
        /// </summary>
        internal static string REQ_GET_EVENTS {
            get {
                return ResourceManager.GetString("REQ_GET_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT * FROM activite ORDER BY idAct;.
        /// </summary>
        internal static string REQ_GETACTIVITIES {
            get {
                return ResourceManager.GetString("REQ_GETACTIVITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SELECT * FROM offre O INNER JOIN activite A ON O.idAct = A.idAct INNER JOIN typecontrat T ON O.idContrat = T.idContrat INNER JOIN utilisateur U ON O.idEmployeur = U.idUser AND U.idStatut &gt; 1;.
        /// </summary>
        internal static string REQ_GETOFFERS {
            get {
                return ResourceManager.GetString("REQ_GETOFFERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INSERT INTO activite(intitAct, estActif) VALUES(@intitAct, @estActif);.
        /// </summary>
        internal static string REQ_INSERT_ACTIVITY {
            get {
                return ResourceManager.GetString("REQ_INSERT_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UPDATE activite SET intitAct = @intitAct, estActif = @estActif WHERE idAct = @idAct;.
        /// </summary>
        internal static string REQ_UPDATE_ACTIVITY {
            get {
                return ResourceManager.GetString("REQ_UPDATE_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UPDATE activite SET estActif = @estActif WHERE idAct = @idAct;.
        /// </summary>
        internal static string REQ_UPDATE_ACTIVITY_DISPLAYING {
            get {
                return ResourceManager.GetString("REQ_UPDATE_ACTIVITY_DISPLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UPDATE offre SET estRetire = @estRetire WHERE idOffre = @id ;.
        /// </summary>
        internal static string REQ_UPDATE_OFFER_DISPLAYING {
            get {
                return ResourceManager.GetString("REQ_UPDATE_OFFER_DISPLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UPDATE offre SET estValide = @estValide WHERE idOffre = @id ;.
        /// </summary>
        internal static string REQ_UPDATE_OFFER_VALIDITY {
            get {
                return ResourceManager.GetString("REQ_UPDATE_OFFER_VALIDITY", resourceCulture);
            }
        }
    }
}
